### ISSUE TITLE
直接卸载，在点安装后出现如下问题

### ISSUE THREAD

**Issue by tanyo520** [lamondlu/CoolCat#35]
RuntimeBinderException: Cannot convert type 'System.Collections.Generic.List<DemoPlugin1.Models.BookViewModel>' to 'System.Collections.Generic.List<DemoPlugin1.Models.BookViewModel>'
CallSite.Target(Closure , CallSite , object )

**Comment by tanyo520** [comment]
感觉是unload的时候没卸载掉

**Comment by lamondlu** [comment]
Duplicate of #22

**Comment by lamondlu** [comment]
参见问题22， 确实是没完全卸载掉。应该是预编译视图的缓存问题，重新安装之后的类型和缓存的类型处于2个ALC中，所以运行时认为类型不同。临时的解决方案是不是用强类型，使用dynamic, 这个的缺点是视图中就没有代码提示了。
后续会更新这一部分，可以参考临时方案暂时解决一下

**Comment by lamondlu** [comment]
@tanyo520 暂时将razor视图顶部的强类型model声明去掉就不会有问题了

**Comment by tanyo520** [comment]
> Duplicate of 

> 参见问题22， 确实是没完全卸载掉。应该是预编译视图的缓存问题，重新安装之后的类型和缓存的类型处于2个ALC中，所以运行时认为类型不同。临时的解决方案是不是用强类型，使用dynamic, 这个的缺点是视图中就没有代码提示了。
> 后续会更新这一部分，可以参考临时方案暂时解决一下
好像去掉转换确实可以， 感谢！

**Comment by tanyo520** [comment]
> @tanyo520 暂时将razor视图顶部的强类型model声明去掉就不会有问题了

大佬有木有这个项目的官方群，对这个项目很感兴趣
